name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: fix error
      run: sudo chmod 755 'scripts/macos.sh'
    - name: get dependencies
      run: scripts/macos.sh
    - name: make all
      run: make all
